# Generated by Django 4.2.3 on 2023-07-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makelink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
                ('uuid', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
